name: dev deployment
on:
  push:
    branches:
      - main

env:
  DEPLOY_ENV: "dev"
  AWS_DEFAULT_REGION: "us-east-1"
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID_DEV }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN_DEV }}

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: echo "start install"
      - run: npm install --prefix  ../src/file-upload-trigger
      - run: npm install --prefix  ../src/layers/common/3rd-party/nodejs/node14
      - run: npm install
      - run: echo "completed install"
      - name: pulumi up
        uses: pulumi/actions@v3
        with:
          command: up
          stack-name: ${{ env.DEPLOY_ENV }}
          work-dir: ./infra